#!/bin/bash


to_namespace=`oc ns -c`
while getopts h:i:t: flag
do
    case "${flag}" in
        h) host=${OPTARG};;
        i) interface=${OPTARG};;
        t) to_namespace=${OPTARG};;
    esac
done

echo "host: $host";
echo "interface: $interface";
echo "to_namespace: $to_namespace";


NODE=$host
INTERFACE=$interface
TO_NAMESPACE=$to_namespace


cmd_in_host() {
    oc debug node/$NODE -n $TO_NAMESPACE -- chroot /host $@
}

cmd_in_toolbox() {
    oc debug node/$NODE -n $TO_NAMESPACE -- $@
}


echo ""

FILENAME="/host/var/tmp/${NODE}_${INTERFACE}_$(date +%d_%m_%Y-%H_%M_%S-%Z).pcap"
echo "pcap for interface ${INTERFACE} of node ${NODE} in ${FILENAME}"
echo ""

cmd_in_toolbox tcpdump -nn -s 0 -i $INTERFACE -w $FILENAME 


